# main text of home
name: Eshin Jolly
bio: Postdoctoral Fellow at Dartmouth College
url: https://eshinjolly.com

picture: assets/images/slices.png
twitter: Eshjolly
linkedin: eshin-jolly-phd-164863a1
github: ejolly
email: eshin.jolly@gmail.com
cv: /assets/pdfs/JollyCV.pdf
analytics-google: 'UA-68163011-2'

about: true
blog: true
pubs: true
music: true
research: true
software: true

permalink: pretty
markdown: kramdown
highlighter: rouge
read-time: true
show-tags: true
related: false
blog-nav-links: false
show-author: false
compress_html:
  clippings: all
  comments: all
  endings: all
  blanklines: true
  profile: false

plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-paginate
  - jekyll-postcss

postcss:
  cache: false

exclude: ["convert_notebooks.sh", "npm-debug.log", "package.json", "package-lock.json",
"postcss.config.js", "Rakefile", "README.md", "tailwind.config.js", "assets/drafts",
"pubs.md", "LICENSE", "tags", "projects"]
destination: ./docs