# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Eshin Jolly
tagline:          
name:             Eshin Jolly
description:      Graduate Student at Dartmouth College
url:              
baseurl:          /


# Custom vars
version:          1.0.0

github:
  repo:           

